# Generated by Django 4.2.16 on 2024-10-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finansas', '0002_alter_movimiento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
